### ISSUE TITLE
No longer works with Facebook API v2.0

### ISSUE THREAD

**Issue by ShubhamBadal** [tusharmakkar08/Facebook_Graph_Search_Images#1]
This was cool! Used it for stalking crushes! :p
But I think this no longer works because of changes in Graph API
https://developers.facebook.com/docs/apps/changelog
Any ideas or possible hacks to solve this issue?

**Comment by tusharmakkar08** [comment]
Yeah, due to change in the Graph API this doesn't work. Work Around this is to fetch `profileId` through sites like : http://findmyfbid.com/ and then pass it to the `open_image_page` function . Haven't got time to  modify the code . Feel free to update it .

**Comment by tusharmakkar08** [comment]
Modified it so that it works with the API Change.
